

 const EducationalMaterial= [
  { class: '9th', subject: 'Physics', chapter: 'Chapter 5' },
  { class: '11th', subject: 'Math', chapter: 'Chapter 10' },
  { class: '8th', subject: 'History', chapter: 'Chapter 1' },
  { class: '10th', subject: 'Geography', chapter: 'Chapter 3' },
  { class: '12th', subject: 'Literature', chapter: 'Chapter 8' },
  { class: '7th', subject: 'Physics', chapter: 'Chapter 2' },
  { class: '11th', subject: 'History', chapter: 'Chapter 6' },
  { class: '9th', subject: 'Math', chapter: 'Chapter 4' },
  { class: '8th', subject: 'Geography', chapter: 'Chapter 7' },
  { class: '10th', subject: 'Physics', chapter: 'Chapter 9' },
  { class: '12th', subject: 'Math', chapter: 'Chapter 5' },
  { class: '9th', subject: 'Geography', chapter: 'Chapter 3' },
  { class: '11th', subject: 'Literature', chapter: 'Chapter 8' },
  { class: '7th', subject: 'History', chapter: 'Chapter 2' },
  { class: '10th', subject: 'Physics', chapter: 'Chapter 6' },
  { class: '8th', subject: 'Math', chapter: 'Chapter 4' },
  { class: '12th', subject: 'Geography', chapter: 'Chapter 7' },
  { class: '9th', subject: 'Physics', chapter: 'Chapter 9' },
  { class: '11th', subject: 'Literature', chapter: 'Chapter 5' },
  { class: '7th', subject: 'History', chapter: 'Chapter 3' },
  { class: '10th', subject: 'Math', chapter: 'Chapter 8' },
  { class: '8th', subject: 'Geography', chapter: 'Chapter 2' },
  { class: '12th', subject: 'Physics', chapter: 'Chapter 6' },
  { class: '9th', subject: 'History', chapter: 'Chapter 4' },
  { class: '11th', subject: 'Math', chapter: 'Chapter 7' },
  { class: '7th', subject: 'Geography', chapter: 'Chapter 9' },
  { class: '10th', subject: 'Literature', chapter: 'Chapter 5' },
  { class: '8th', subject: 'Physics', chapter: 'Chapter 3' },
  { class: '12th', subject: 'History', chapter: 'Chapter 8' },
  { class: '9th', subject: 'Math', chapter: 'Chapter 2' },
  { class: '11th', subject: 'Geography', chapter: 'Chapter 6' },
  { class: '7th', subject: 'Physics', chapter: 'Chapter 4' },
  { class: '10th', subject: 'History', chapter: 'Chapter 7' },
  { class: '8th', subject: 'Math', chapter: 'Chapter 9' },
  { class: '12th', subject: 'Geography', chapter: 'Chapter 5' },
  { class: '9th', subject: 'Literature', chapter: 'Chapter 3' },
  { class: '11th', subject: 'History', chapter: 'Chapter 8' },
  { class: '7th', subject: 'Math', chapter: 'Chapter 2' },
  { class: '10th', subject: 'Geography', chapter: 'Chapter 6' },
  { class: '8th', subject: 'Physics', chapter: 'Chapter 4' },
  { class: '12th', subject: 'History', chapter: 'Chapter 7' },
  { class: '9th', subject: 'Math', chapter: 'Chapter 9' },
  { class: '11th', subject: 'Literature', chapter: 'Chapter 5' },  
]

  

export default EducationalMaterial